# Generated by Django 5.2 on 2025-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='verification_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
