# Generated by Django 5.2 on 2025-05-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_notification_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
