services:
  web:
    build: .
    container_name: django
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
