name: ntu_web
services:
  web:
    build: .
    container_name: django
    ports:
      - "8000:80"
    env_file:
      - .env
    # remove this in production
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    # remove this in production
    command: ["python", "manage.py", "runserver", "0.0.0.0:80"]

  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

volumes:
  db_data:
