# Generated by Django 5.2 on 2025-04-24 00:43

import Transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='slug',
            field=models.CharField(default=Transaction.models.generate_random_slug, editable=False, max_length=10, unique=True),
        ),
    ]
