# Generated by Django 5.2 on 2025-05-13 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0003_repaymentrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RepaymentRequest',
        ),
    ]
