# Generated by Django 5.2 on 2025-05-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0007_alter_paymentverification_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentverification',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('line_pay', 'Line Pay'), ('bank_transfer', 'Bank Transfer')], max_length=50),
        ),
    ]
