# Generated by Django 5.2 on 2025-05-17 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transaction', '0006_alter_expenseshare_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentverification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='Transaction.transaction'),
        ),
    ]
